### ISSUE TITLE
Score, Quality, Difficulty and Popularity should be converted into components

### ISSUE THREAD

**Issue by JamesDonnelly** [GradedMetrics/ui#22]
These values are used across various pages and if we wanted to make a change to any of them it would require changing multiple things (if we remember they exist in those places). This could be improved if we created components for each:

### Key acceptance criteria
- [ ] There should be a `<Score />` component which takes the `score` value and outputs the score in the format `{score}`;
- [ ] There should be a `<Quality />` component which takes the `quality` value and outputs the quality in the format `{quality}%`;
- [ ] There should be a `<Difficulty />` component which takes the `difficulty` and `difficultySampleSize` values and outputs the difficulty in the format `{difficulty}% ({psa10Count}/{difficultySampleSize})`†;
- [ ] There should be a `<Popularity />` component which takes the `popularity` and outputs the popularity in the format `#{popularity}`.

† `psa10Count` can be derived by determining the inverse of the difficulty percentage against the difficulty sample size.

**Comment by jcooke1986uk** [comment]
@JamesDonnelly This is why I made separate components, because you've set it as the criteria.
I'll need to update the components here to reflect the quality % and new difficultySampleSize.
Are we even still doing popularity as part of the scores?
