### ISSUE TITLE
Implement the 'cards by score' page

### ISSUE THREAD

**Issue by JamesDonnelly** [GradedMetrics/ui#23]
### User requirement
I would like to be able to see what the overall most difficult cards to grade are. A new endpoint has been implemented, `/cards-by-score` which reveals the top 50 cards across all sets.

### Key acceptance criteria
- [x] A new top-level page 'Cards by Score' should be added (name subject to change);
- [x] The new page should show the user the list of cards, with possible sorting options for set name, year, etc.

**Comment by jcooke1986uk** [comment]
Is the second point on this complete as the sorting at the moment is only Rank, Rank change, Difficulty, and Volatility?
