### ISSUE TITLE
Chart: Population over time

### ISSUE THREAD

**Issue by JamesDonnelly** [GradedMetrics/ui#4]
### User requirement
As a user I would like to see how the population of a given card has changed over time.

### Key acceptance criteria
- [x] Find a charting library to use
- [x] Implement a lightweight chart which can be displayed in the set and card lists
- [x] Implement a full population chart which can be displayed on the set and card headers

**Comment by jcooke1986uk** [comment]
@JamesDonnelly are we doing population charts in the header for the Sets page and the Set page?
