### ISSUE TITLE
Implement scoring

### ISSUE THREAD

**Issue by jcooke1986uk** [GradedMetrics/ui#7]
### User requirement
As a user I would like to be able to see at a glance what score GM has given to a set based on its Quality, Popularity, and Difficulty.

### Key acceptance criteria
- [x] https://github.com/GradedMetrics/api/issues/1 - API to be completed first
- [x] Implement scoring on UI

**Comment by JamesDonnelly** [comment]
Scoring is now returned from the API and implemented on the /sets page. It still needs implementing on an individual set's card list page.
